apiVersion: v2
name: smarthome-metrics-temperature
description: A Helm chart for Kubernetes
type: application
version: "0.2.0"

dependencies:
  - name: rails-application
    version: "0.2.1"
    repository: https://klausmeyer.github.io/helm-charts
