apiVersion: v2
name: docker-registry-browser
description: Web Interface for the Docker Registry HTTP API V2 written in Ruby on Rails.
type: application
version: "0.4.0"

dependencies:
  - name: rails-application
    version: "0.2.1"
    repository: https://klausmeyer.github.io/helm-charts
