apiVersion: v2
name: oopsy
description: A Helm chart for Kubernetes
type: application
version: "0.2.0"

dependencies:
  - name: rails-application
    version: "0.2.1"
    repository: https://klausmeyer.github.io/helm-charts

  - name: redis
    version: "2.2.1"
    repository: https://groundhog2k.github.io/helm-charts
