apiVersion: v2
name: whatchy
description: A Helm chart for Kubernetes
type: application
version: "0.3.1"

dependencies:
  - name: rails-application
    version: "0.2.1"
    repository: https://klausmeyer.github.io/helm-charts
